### ISSUE TITLE
Console warn on mark hover

### ISSUE THREAD

**Issue by luisxcam** [vega/vega-tooltip#117]
Getting a warn message on the console, but it works perfectly fine on the app. The tooltip is being displayed correctly and the field exists in the data.
```js
var opt = {
    "mode": "vega-lite"
};
vega.embed("#vegavis", vlSpec, opt, function (error, result) {
    var tooltipOpt = {
        showAllFields: false,
        fields: [
            { field: "ProjectID", title:"Project ID" },
            { field: "Name", title:"Name" },
        ]
    };
    vegaTooltip.vegaLite(result.view, vlSpec, tooltipOpt);
    console.log(result.view.data("data_1"));
});
```
![console](https://user-images.githubusercontent.com/8656595/27658293-88d8145a-5c1d-11e7-8416-8d05773ff672.JPG)
![projectid](https://user-images.githubusercontent.com/8656595/27658465-23d12708-5c1e-11e7-96a2-aafa287d9d86.jpg)
![projectidtooltip](https://user-images.githubusercontent.com/8656595/27658531-5dcf0de4-5c1e-11e7-9256-c42ee641818b.jpg)

**Comment by luisxcam** [comment]
Adding sample code for analysis
[example.zip](https://github.com/vega/vega-tooltip/files/1112404/example.zip)

**Comment by domoritz** [comment]
Can you create a gist by forking https://bl.ocks.org/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9?

**Comment by luisxcam** [comment]
done
http://blockbuilder.org/luisxcam/78be4f377f55175ffe65ba24daf8dae2

**Comment by luisxcam** [comment]
I figured that it has issues when there's a vconcat element. If you check the example.zip file you will see that I'm doing a dual vis

**Comment by domoritz** [comment]
I think you forgot to save: https://bl.ocks.org/luisxcam/78be4f377f55175ffe65ba24daf8dae2

**Comment by domoritz** [comment]
If the problem is multiview displays, this is a duplicate of https://github.com/vega/vega-tooltip/issues/108

**Comment by luisxcam** [comment]
I see, sorry for that. Then, I'll wait

**Comment by domoritz** [comment]
It may not be. I just made a hypothesis. If you update the gist, I will confirm.

**Comment by luisxcam** [comment]
Updated

**Comment by domoritz** [comment]
Perfect. Yes, the issue is definitely with multiview composition. The good news is that you can just ignore the warning for now. I hope that's okay.
